FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /app

# Copiar csproj y restaurar como capas distintas
COPY *.csproj ./
RUN dotnet restore

# Copiar todo lo demás y construir
COPY . ./
RUN dotnet publish -c Release -o out

# Construir la imagen de tiempo de ejecución
FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "MyBackend_MongoDB_CSharp.dll"]


