# Etapa de construcción
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-env
WORKDIR /app

# Copiar los archivos de la solución y restaurar las dependencias
COPY ./*.sln ./
COPY ./*.csproj ./
#COPY ./Store.Backend/*.csproj ./Store.Backend/


# Restaurar las dependencias
RUN dotnet restore

# Copiar todo el código fuente y compilar la aplicación
COPY . ./
RUN dotnet publish -c Release -o out

# Etapa de tiempo de ejecución
FROM mcr.microsoft.com/dotnet/aspnet:7.0
WORKDIR /app
COPY --from=build-env /app/out .

#set entry point 
ENTRYPOINT ["dotnet", "MyBackend_MongoDB_CSharp.dll"]


